### ISSUE TITLE
Exec 'ensure_correct_permissions' occurs before kibana user/group is created

### ISSUE THREAD

**Issue by landerson61** [evenup/evenup-kibana#62] opened 2015-11-23 13:31 UTC
The following permissions exec can sometimes run before the kibana user & group are created causing the exec to fail:

```
exec { 'ensure_correct_permissions':
    command     => "chown -R ${user}:${group} ${install_path}/${filename}",
    path        => ['/bin', '/sbin'],
    refreshonly => true,
    require     => Exec['extract_kibana'],
}
```

This can result in the following error:

```
Info: Applying configuration version '1448284622'
Notice: /Stage[main]/Profiles::Kibana4_users/Firewall[007 allow kibana]/ensure: created
Notice: /Stage[main]/Kibana::Install/File[kibana-init-script]/ensure: defined content as '{md5}99a7ae5ae22750df6dc88382167f3cd9'
Info: /Stage[main]/Kibana::Install/File[kibana-init-script]: Scheduling refresh of Class[Kibana::Service]
Notice: /Stage[main]/Kibana::Install/Wget::Fetch[kibana]/Exec[wget-kibana]/returns: executed successfully
Notice: /Stage[main]/Kibana::Install/Exec[extract_kibana]/returns: executed successfully
Info: /Stage[main]/Kibana::Install/Exec[extract_kibana]: Scheduling refresh of Exec[ensure_correct_permissions]
Notice: /Stage[main]/Kibana::Install/Exec[ensure_correct_permissions]/returns: chown: invalid user: `kibana:kibana'
Error: /Stage[main]/Kibana::Install/Exec[ensure_correct_permissions]: Failed to call refresh: chown -R kibana:kibana /usr/local/kibana-4.2.1-linux-x64 returned 1 instead of one of [0]
Error: /Stage[main]/Kibana::Install/Exec[ensure_correct_permissions]: chown -R kibana:kibana /usr/local/kibana-4.2.1-linux-x64 returned 1 instead of one of [0]
Notice: /Stage[main]/Kibana::Install/File[/usr/local/kibana]/ensure: created
Notice: /Stage[main]/Kibana::Install/Group[kibana]/ensure: created
Notice: /Stage[main]/Kibana::Install/User[kibana]/ensure: created
Notice: /Stage[main]/Kibana::Install/File[/var/log/kibana]/ensure: created
```

Notice the order in which the error appears before Group & User creation.

Thanks

**Comment by ltutar** [comment] 2015-11-25 14:05
I do not see the same behaviour on my machine
```
Notice: /Stage[main]/Kibana::Install/Wget::Fetch[kibana]/Exec[wget-kibana]/returns: executed successfully
Notice: /Stage[main]/Kibana::Install/Exec[extract_kibana]/returns: executed successfully
Info: /Stage[main]/Kibana::Install/Exec[extract_kibana]: Scheduling refresh of Exec[ensure_correct_permissions]
Notice: /Stage[main]/Kibana::Install/Exec[ensure_correct_permissions]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Kibana::Install/File[/opt/kibana]/ensure: created
Info: Class[Kibana::Install]: Scheduling refresh of Class[Kibana::Service]
```

**Comment by landerson61** [comment] 2015-11-27 11:21
Maybe you already had kibana user & group created prior to this puppet run? Try completely removing kibana along with both kibana user & group from your system, then run puppet again?

**Comment by gdhbashton** [comment] 2015-11-27 14:46
Puppet resource ordering is completely non-deterministic before 4.x - it's luck of the draw whether or not you will run into this problem.  I just experienced it using puppet 3.8.4:

```
    amazon-ebs: Notice: /Stage[main]/Kibana::Install/Exec[extract_kibana]/returns: executed successfully
    amazon-ebs: Info: /Stage[main]/Kibana::Install/Exec[extract_kibana]: Scheduling refresh of Exec[ensure_correct_permissions]
    amazon-ebs: Notice: /Stage[main]/Kibana::Install/File[/opt/kibana]/ensure: created
    amazon-ebs: Notice: /Stage[main]/Kibana::Install/Exec[ensure_correct_permissions]/returns: chown: invalid user: ‘kibana:kibana’
    amazon-ebs: Error: /Stage[main]/Kibana::Install/Exec[ensure_correct_permissions]: Failed to call refresh: chown -R kibana:kibana /opt/kibana-4.1.3-linux-x64 returned 1 instead of one of [0]
    amazon-ebs: Error: /Stage[main]/Kibana::Install/Exec[ensure_correct_permissions]: chown -R kibana:kibana /opt/kibana-4.1.3-linux-x64 returned 1 instead of one of [0]

```

If I specify the extra `require` on Exec['extract_kibana'],`  then the problem is solved:

```
    amazon-ebs: Notice: /Stage[main]/Kibana::Install/Group[kibana]/ensure: created
    amazon-ebs: Notice: /Stage[main]/Kibana::Install/User[kibana]/ensure: created
    amazon-ebs: Notice: /Stage[main]/Kibana::Install/File[/var/log/kibana]/ensure: created
    amazon-ebs: Notice: /Stage[main]/Kibana::Install/Wget::Fetch[kibana]/Exec[wget-kibana]/returns: executed successfully
    amazon-ebs: Notice: /Stage[main]/Kibana::Install/Exec[extract_kibana]/returns: executed successfully
    amazon-ebs: Info: /Stage[main]/Kibana::Install/Exec[extract_kibana]: Scheduling refresh of Exec[ensure_correct_permissions]
    amazon-ebs: Notice: /Stage[main]/Kibana::Install/File[/opt/kibana]/ensure: created
    amazon-ebs: Notice: /Stage[main]/Kibana::Install/Exec[ensure_correct_permissions]: Triggered 'refresh' from 1 events

```

**Comment by jlambert121** [comment] 2015-11-29 19:07
I believe this is resolved in master as well: https://github.com/evenup/evenup-kibana/blob/master/manifests/install.pp#L58

**Closed by jlambert121** 2015-11-29 19:07 UTC
